// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: wrap_indev

#ifndef _WRAP_INDEV_UI_H
#define _WRAP_INDEV_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void AnimFocus_Animation(lv_obj_t * TargetObject, int delay);
void AnimDeFocus_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_ScreenHome
void ui_ScreenHome_screen_init(void);
extern lv_obj_t * ui_ScreenHome;
void ui_event_TextAreaSerialNumber(lv_event_t * e);
extern lv_obj_t * ui_TextAreaSerialNumber;
extern lv_obj_t * ui_LabelStatus;
extern lv_obj_t * ui_SpinnerStatus;
void ui_event_SwitchTheme(lv_event_t * e);
extern lv_obj_t * ui_SwitchTheme;
extern lv_obj_t * ui____initial_actions0;



LV_FONT_DECLARE(ui_font_NotoSansSCMedium24);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
