// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: wrap_indev

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void lv_event_to_dark_theme(lv_event_t * e);
void lv_event_to_light_theme(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
