// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: wrap_indev

#include "../ui.h"

void ui_ScreenHome_screen_init(void)
{
    ui_ScreenHome = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenHome, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenHome, lv_color_hex(0x9A332B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ScreenHome, lv_color_hex(0xE17100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ScreenHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ScreenHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ScreenHome, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaSerialNumber = lv_textarea_create(ui_ScreenHome);
    lv_obj_set_width(ui_TextAreaSerialNumber, 300);
    lv_obj_set_height(ui_TextAreaSerialNumber, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_x(ui_TextAreaSerialNumber, 0);
    lv_obj_set_y(ui_TextAreaSerialNumber, -80);
    lv_obj_set_align(ui_TextAreaSerialNumber, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaSerialNumber, "取件码/运单号后六位");
    lv_textarea_set_one_line(ui_TextAreaSerialNumber, true);
    lv_obj_set_style_text_align(ui_TextAreaSerialNumber, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaSerialNumber, &ui_font_NotoSansSCMedium24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TextAreaSerialNumber, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextAreaSerialNumber, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextAreaSerialNumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TextAreaSerialNumber, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_TextAreaSerialNumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TextAreaSerialNumber, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TextAreaSerialNumber, 1, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_LabelStatus = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_LabelStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStatus, 0);
    lv_obj_set_y(ui_LabelStatus, 80);
    lv_obj_set_align(ui_LabelStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStatus, "正在查询中");
    lv_obj_set_style_text_color(ui_LabelStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelStatus, &ui_font_NotoSansSCMedium24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinnerStatus = lv_spinner_create(ui_ScreenHome, 1000, 90);
    lv_obj_set_width(ui_SpinnerStatus, 30);
    lv_obj_set_height(ui_SpinnerStatus, 30);
    lv_obj_set_x(ui_SpinnerStatus, 0);
    lv_obj_set_y(ui_SpinnerStatus, 40);
    lv_obj_set_align(ui_SpinnerStatus, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpinnerStatus, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_SpinnerStatus, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_SpinnerStatus, lv_color_hex(0x83373B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpinnerStatus, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpinnerStatus, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_SpinnerStatus, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_SwitchTheme = lv_switch_create(ui_ScreenHome);
    lv_obj_set_width(ui_SwitchTheme, 50);
    lv_obj_set_height(ui_SwitchTheme, 25);
    lv_obj_set_x(ui_SwitchTheme, 200);
    lv_obj_set_y(ui_SwitchTheme, 135);
    lv_obj_set_align(ui_SwitchTheme, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SwitchTheme, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SwitchTheme, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SwitchTheme, lv_color_hex(0x535353), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SwitchTheme, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_radius(ui_SwitchTheme, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SwitchTheme, lv_color_hex(0x303030), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SwitchTheme, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_TextAreaSerialNumber, ui_event_TextAreaSerialNumber, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchTheme, ui_event_SwitchTheme, LV_EVENT_ALL, NULL);

}
